logging:
    path: logs/
    level:  
        uk.co.landbit: DEBUG
        org.springframework: INFO

twittertofeed:
    tweetindexer:
        scheduler: 180000
---

spring:
    
    profiles: scratch
    redis:
        host: 192.168.1.72
        port: 6379
        password: 
        pool:
            max-wait: -1
            max-active: -1
            max-idle: -1
            min-idle: 16
    datasource:
        driver-class-name: org.hsqldb.jdbc.JDBCDriver
        url: jdbc:hsqldb:mem:scratchdb
        validation-query: select 1;
        # add some custom hikari pool related properties
        custom-hikari-minimun-idle: 8
        custom-hikari-max-pool-size: 32
        custom-hikari-connection-timeout: 30000
    jpa:
        show-sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: create-drop
            #naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.dialect: 
            hibernate.hbm2ddl.import_files:
            #hibernate.hbm2ddl.import_files: import.sql

---

spring:
    profiles: live
    # Override in config folder
    social:
        twitter:
            app-id: myappid
            app-secret: myappsecret
    redis:
        host: 192.168.1.72
        port: 6379
        password: 
        pool:
            max-wait: -1
            max-active: -1
            max-idle: -1
            min-idle: 16
    datasource:
        driver-class-name: org.mariadb.jdbc.MySQLDataSource
        url: jdbc:mysql://localhost:3306/twittertofeed
        username: twittertofeed
        password: averycomplicatedpassword
        test-on-borrow: true
        test-while-idle: true
        validation-query: select 1;
        # add some custom hikari pool related properties
        custom-hikari-minimun-idle: 8
        custom-hikari-max-pool-size: 32
        custom-hikari-connection-timeout: 30000
    jpa:
        show-sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: validate
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.dialect: 
            hibernate.hbm2ddl.import_files: 
#            hibernate.connection.provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
#            hibernate.hikari.minimumIdle: 20
#            hibernate.hikari.maximumPoolSize: 100
#            hibernate.hikari.idleTimeout: 30000
#            hibernate.hikari.dataSourceClassName: net.sourceforge.jtds.jdbc.Driver